version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --no-include-email --region ap-south-1 | docker login --username AWS --password-stdin 986849786625.dkr.ecr.ap-south-1.amazonaws.com 
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t wordpress:v1
      - echo "Tagging Docker image..."
      - docker tag wordpress:v1 986849786625.dkr.ecr.ap-south-1.amazonaws.com:latest
  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push 986849786625.dkr.ecr.ap-south-1.amazonaws.com/wordpress:latest

artifacts:
  files: []
